import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
      <title>NextJS - Mongo Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
          <header id="head">
            <div className="banner-content">
              <h1> NextJS - Mongo Auth</h1>
            </div>
          </header>
        </div>

      
    </div>
  )
}
